vpc-name      = "Jenkins-proj1-vpc"
igw-name      = "Jenkins-proj1-igw"
subnet-name   = "Jenkins-proj1-subnet"
rt-name       = "Jenkins-proj1-route-table"
sg-name       = "Jenkins-proj1-sg"
instance-name = "Jenkins-server"
key-name      = "Linux_harish_pem"
iam-role      = "my-dev-proj-1"
